# Generated by Django 4.2.1 on 2023-06-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_card', '0003_alter_bankcard_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
